trigger:
- main

pool:
  vmImage: 'windows-latest'

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - script: echo "Build stage"
            displayName: 'Dummy Build Step'

  - stage: Test
    dependsOn: Build
    jobs:
      - job: TestJob
        steps:
          - script: echo "Test stage"
            displayName: 'Dummy Test Step'

  - stage: CodeAnalysis
    dependsOn: Test
    jobs:
      - job: CodeAnalysisJob
        steps:
          - script: echo "Code Analysis stage"
            displayName: 'Dummy Code Analysis Step'

  - stage: Package
    dependsOn: CodeAnalysis
    jobs:
      - job: PackageJob
        steps:
          - script: echo "Package stage"
            displayName: 'Dummy Package Step'

  - stage: Deploy
    dependsOn: Package
    jobs:
      - job: DeployJob
        steps:
          - script: echo "Deploy stage"
            displayName: 'Dummy Deploy Step'
